const FontClassMap = {
  "Arial": "font-arial",
  "Verdana": "font-verdana",
  "Tahoma": "font-tahoma",
  "Trebuchet MS": "font-trebuchet",
  "Georgia": "font-georgia",
  "Times New Roman": "font-times",
  "Palatino Linotype": "font-palatino",
  "Garamond": "font-garamond",
  "Courier New": "font-courier",
  "Lucida Sans Unicode": "font-lucida",
  "Impact": "font-impact",
  "Segoe UI": "font-segoe",
  "Optima": "font-optima",
  "Gill Sans": "font-gillsans",
  "Century Gothic": "font-century",
  "Inter": "font-inter",
  "Roboto": "font-roboto",
  "Open Sans": "font-opensans",
  "Lato": "font-lato",
  "Montserrat": "font-montserrat",
  "Poppins": "font-poppins",
  "Source Sans Pro": "font-sourcesans",
  "Nunito": "font-nunito",
  "Raleway": "font-raleway",
  "Ubuntu": "font-ubuntu",
  "Playfair Display": "font-playfair",
  "Merriweather": "font-merriweather",
  "Roboto Slab": "font-robotoslab",
  "Oswald": "font-oswald",
  "Fira Sans": "font-firasans",
  "Work Sans": "font-worksans",
  "Quicksand": "font-quicksand",
  "DM Sans": "font-dmsans",
  "Josefin Sans": "font-josefin",
  "Pacifico": "font-pacifico",
  "Space Mono": "font-spacemono"
};

export default FontClassMap;